import { Toaster } from "react-hot-toast";
import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";

export const metadata = {
  title: "Todo App Using next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster/>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
